### ISSUE TITLE
Elements no longer displayed for users that are not logged in.

### ISSUE THREAD

**Issue by nlighteneddesign** [silverstripe/silverstripe-elemental#786]
### Overview

We use elements heavily on our site, After updating to 4.3.2, certain pages no longer show their elements to users that are not authenticated. Logged in users see the content as expected.

Silverstripe 4.5.2
Elemental 4.3.2

### Guide to replicate

- Permission settings
  - All pages were set to inherit from parent page.
  - The parent was set to inherit from site settings.
  - The site settings were set to anyone.
- See comments below for further details

### ACs
- Add some new unit tests to cover various permutations of permissions
- Fix the thing =)

**Comment by ScopeyNZ** [comment]
What version did you update from?

**Comment by nlighteneddesign** [comment]
4.3.1 to 4.3.2 for elemental
4@dev to 4.5 for the framework

**Comment by nlighteneddesign** [comment]
Ok we were able to find a work around.

All pages were set to inherit from parent page.
The parent was set to inherit from site settings.

The site settings were set to anyone.
Changing the parent page to anyone, then back to inherit site settings fixed all of the access issues for anonymous users.

**Comment by brynwhyman** [comment]
> certain pages no longer show their elements to users that are not authenticated.

Hey @nlighteneddesign, by this do you mean that non-authenticated users cannot see published elements?

**Comment by nlighteneddesign** [comment]
@brynwhyman yes, unauthenticated users were unable to see published elements.

**Comment by bergice** [comment]
Thanks for updating us.

Closing this for now seeing as it was resolved. Will reopen if this happens for other people.

**Comment by tomaszpirc** [comment]
I can confirm that this is an issue.

- The content of the page is displayed for anonymous user as it should be, except for elemental modules. When user logs in elemental modules are also displayed.   
- The situation can be resolved by using the steps from the @nlighteneddesign comment https://github.com/dnadesign/silverstripe-elemental/issues/786#issuecomment-606203079 
- I could not check if the situation remains resolved or the same elements can become 'invisible' again after the above solution is applied.

This is annoying especially for sites with many pages where it is hard to track down all pages with hidden element modules.

**Comment by elliot-sawyer** [comment]
Can confirm, this is still an issue for us on 4.3.2. If set to "Inherit", only logged in users can view elements. Setting the parent to "Anyone" resolves the issue. Changing it back removes them from view.

**Comment by brynwhyman** [comment]
Reopening issue. Thanks for adding these additional comments.

**Comment by emteknetnz** [comment]
I cannot replicate this issue

Structure:

```
Site Settings (View: Anyone)
- Page (Inherit)
  - Block Page (Inherit)
    - Content Block
```

Template:
(contains `$ElementalArea`)

composer.json:
```
    "require": {
        "php": ">=7.1.0",
        "silverstripe-themes/simple": "^3",
        "silverstripe/recipe-plugin": "^1",
        "silverstripe/recipe-content-blocks": "2.5.x-dev",
        "silverstripe/recipe-cms": "4.5.2 as 4.5.x-dev",
        "dnadesign/silverstripe-elemental": "4.3.2 as 4.3.x-dev"
    },
```

Is someone able to provide some exact replication steps?

**Comment by brynwhyman** [comment]
A similar issue has also been raised, perhaps a duplicate (but with more replication steps?) https://github.com/dnadesign/silverstripe-elemental/issues/823

**Comment by sunnysideup** [comment]
use my test repo as it should be easy to fix with that.

**Comment by Cheddam** [comment]
@nlighteneddesign @tomaszpirc @elliot-sawyer We released Elemental 4.4.1 last week with a fix for #823. Could you try updating and let us know whether this resolves your issue?

**Comment by sunnysideup** [comment]
Thank you for all the work!

**Comment by brynwhyman** [comment]
Looks like this was resolved with the fix for https://github.com/silverstripe/silverstripe-elemental/issues/823
